# Generated by Django 2.1.2 on 2019-09-30 21:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('chatting', '0004_userconsumersession'),
    ]

    operations = [
        migrations.AddField(
            model_name='userconsumersession',
            name='last_seen',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 30, 21, 3, 31, 119499, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userconsumersession',
            name='online',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
