# Generated by Django 2.2.6 on 2019-11-05 12:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfileDetails',
            fields=[
                ('userprofileid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='+', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('dob', models.TextField()),
                ('sex', models.TextField()),
                ('nationality', models.TextField()),
                ('lives_in', models.TextField()),
                ('work', models.TextField()),
                ('education', models.TextField()),
                ('something', models.TextField()),
                ('image_file', models.FileField(upload_to='user_avatar/')),
            ],
        ),
    ]
