# Generated by Django 2.2.6 on 2019-11-05 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofiledetails',
            name='image_file',
            field=models.FileField(upload_to=''),
        ),
    ]
