# Generated by Django 2.2.6 on 2019-11-05 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20191105_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofiledetails',
            name='image_file',
            field=models.FileField(default='/media/user_default_avatar.jpg', upload_to=''),
        ),
    ]
